#! /bin/bash

SHELL_CONF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
THEME_DIR=$shell_config_dir/iTerm2-Color-Schemes/terminator

action=$1
theme=$2

if [ -z ${action+x} ]
then
  if [ $action == 'install' ]
  then
    sudo apt-get install exuberant-ctags
  elif [[ -z ${theme+x} && $action == 'add' ]]
  then
    sed -e '/\[layouts\]/ {
        h
        r '$THEME_DIR/${theme}.config'
        g
        N
    }' \
    ~/shell_config/terminator_config \
    | sed -e '/^$/ d' -e 's/^\[\[.*\]\]/  &/'
  fi
fi
